spring:
  data:
    mongodb:
      uri: mongodb://localhost:27020/customer-db

  kafka:
    bootstrap-servers: localhost:9092


eureka:
  client:
    service-url:
      defaultZone:
        http://eureka:password@localhost:8761/eureka