spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/order-service
    username: vladsw764
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: order-service

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka