spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/order-service
    username: vladsw764
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082
