spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/order-service
    username: vladsw764
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: order-service
  config:
    import: optional:test.properties
  kafka:
    bootstrap-servers: localhost:9092
    topics:
      inventory: inventory-order-topic
      order: order-inventory-topic
      customer: customer-order-topic


server:
  port: 8082


logging:
  level:
    root: INFO
    com.isariev.orderservice: DEBUG
    org.springframework.transaction: DEBUG

eureka:
  client:
    service-url:
      defaultZone:
        http://eureka:password@localhost:8761/eureka

## Resilience4J Configuration


resilience4j:
  circuitbreaker:
    instances:
      order-service:
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        eventConsumerBufferSize: 10
        registerHealthIndicator: true
  retry:
    instances:
      order-service:
        maxAttempts: 3
        waitDuration: 1s
  timelimiter:
    instances:
      order-service:
        timeoutDuration: 5s
        cancelRunningFuture: true

#resilience4j:
#  circuitbreaker:
#    instances:
#      inventory:
#        register-health-indicator: true
#        event-consumer-buffer-size: 10
#        sliding-window-type: COUNT_BASED
#        sliding-window-size: 2
#        failure-rate-threshold: 50
##        wait-duration-in-open-state:
##          seconds: 5 # TODO: check why here error
#        permitted-number-of-calls-in-half-open-state: 3
#
#        automatic-transition-from-open-to-half-open-enabled: false

  ## Timeout config
#  timelimiter:
#    instances:
#      inventory:
##        timeout-duration:
##          seconds: 3

  ## Retry config
#  retry:
#    instances:
#      inventory:
#        max-attempts: 3
##        wait-duration:
##          seconds: 5

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    circuitbreakers:
      enabled: true
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0