spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/inventory-service
    username: vladsw764
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 8083
