spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/inventory-service
    username: vladsw764
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  application:
    name: inventory-service
  kafka:
    bootstrap-servers: localhost:9092


management:
  tracing:
    sampling:
      probability: 1.0

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone:
        http://eureka:password@localhost:8761/eureka


#logger
rest:
  methods:
    logger:
      enabled: true
service:
  methods:
    logger:
      enabled: false
