name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Compile and Build
        run: mvn clean install -DskipTests --batch-mode --update-snapshots

      - name: Create Build Directory
        run: |
          if [ ! -d "build" ]; then
            mkdir build
          fi

      - name: Copy JAR files
        run: |
          cp build/customer-service/customer-service.jar build/discovery-service/discovery-service.jar build/gateway-service/gateway-service.jar build/inventory-service/inventory-service.jar build/order-service/order-service.jar build/

      - name: Upload JAR files
        uses: actions/upload-artifact@v2
        with:
          name: microservices-jars
          path: build
