name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Compile and Build
        run: mvn clean install --batch-mode --update-snapshots

      - name: Copy .jar
        run: mkdir build && cp target/*.jar build

      - uses: actions/upload-artifact@v2
        with:
          name: .jar
          path: build
