name: Java CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Compile and Build
        run: mvn clean install -DskipTests --batch-mode --update-snapshots

      - name: Create Build Directory
        run: mkdir build

      - name: Copy JAR files
        run: cp -r customer-service/target/*.jar build/ && cp -r discovery-service/target/*.jar build/ && cp -r gateway-service/target/*.jar build/ && cp -r inventory-service/target/*.jar build/ && cp -r order-service/target/*.jar build/

      - name: Upload JAR files
        uses: actions/upload-artifact@v2
        with:
          name: microservices-jars
          path: build
